my_string = input('Введите своё имя: ')
print(len(my_string))
print(f'Добро  пожаловать в мир, {my_string}' .upper())
print(f'Добро  пожаловать в мир, {my_string}' .lower())
print(f'Добро  пожаловать в мир, {my_string}' .replace(' ', ''))
print(f'Добро  пожаловать в мир, {my_string}' [0])
print(f'Добро  пожаловать в мир, {my_string}' [-1])